### ISSUE TITLE
Centrer le footer

### ISSUE THREAD

**Issue by Honomatopic** [Honomatopic/Houdinews#11]

**Comment by Honomatopic** [comment]
Bonjour Samuel. J'essaye tant bien que mal de changer la position du footer en CSS ou en ajoutant des classes Bootstrap, mais il reste positionner en bas à droite. Je souhaiterai le centrer sur la page.

**Comment by Honomatopic** [comment]
Bon j'ai réglé le problème je close l'issue

**Comment by samszo** [comment]
bravo beau boulot
