### ISSUE TITLE
le service worker est bien dans bootstrap/js/service-worker.js ?

### ISSUE THREAD

**Issue by Honomatopic** [Honomatopic/Houdinews#12]
le service worker est bien dans bootstrap/js/service-worker.js

**Comment by samszo** [comment]
oui pourquoi pas, il faut juste que le lien soit bon

**Comment by Honomatopic** [comment]
Bon j'ai changé le service worker de place et de position en le mettant à la racine du répertoire pwa. J'ai changé le contenu du fichier aussi. Sur Chrome dans l'onglet Applications il a l'air de tourné sans erreur. Je vais clôturé l'issue.
