### ISSUE TITLE
Le manifest.json est-il bon ?

### ISSUE THREAD

**Issue by Honomatopic** [Honomatopic/Houdinews#13]
Le manifest.json est-il bon ?

**Comment by samszo** [comment]
a priori le manifeste n'est pas bon.
regardes dans chrome les outils de développement onglet application il y a des erreurs

**Comment by Honomatopic** [comment]
Mon manifest.json fonctionne bien maintenant. J'ai vérifié dans la console de Chrome. Je clôture l'issue.
