### ISSUE TITLE
Fenêtre modal boostrap

### ISSUE THREAD

**Issue by Honomatopic** [Honomatopic/Houdinews#14]
Bonjour Samuel. Dans mon template pwa Bootstrap, j'ai envie qu'une fenêtre modal déjà apparu réapparaisse au dessus d'une autre. Mais cela ne marche pas, je voudrais savoir comment on fait avec bootstrap de refaire réapparaitre une fenêtre modal au dessus d'une autre ?

**Comment by samszo** [comment]
une fenêtre dans une fenêtre n'est pas une bonne idée, il vaut mieux remplacer la première fenêtre par une navigation dans une autre page.
voici un exemple qui marche : http://jschr.github.io/bootstrap-modal/ 
cf. exemple Stackable

**Comment by Honomatopic** [comment]
Bonsoir. J'ai réglé l'issue. Je la clôture...
