### ISSUE TITLE
Mise à jour de la base de données projet.sql

### ISSUE THREAD

**Issue by Honomatopic** [Honomatopic/Houdinews#16]
Bonjour. Il faudrait mettre à jour la base de données sur le site en ligne d'Omeka. Le nouveau script SQL de la base de données est disponible sur : https://github.com/Honomatopic/Houdinews/tree/master/bdd

**Comment by samszo** [comment]
Bonjour,
OK la base est à jour.

**Comment by Honomatopic** [comment]
D'accord je clôture l'issue
