### ISSUE TITLE
Vignettes images

### ISSUE THREAD

**Issue by Honomatopic** [Honomatopic/Houdinews#17]
Bonjour. J'ai mis les vignettes pour Omeka dans un répertoire image disponible dans omk/files. Il se trouve ici : https://github.com/Honomatopic/Houdinews/tree/master/omk/files/images. Il faudrait les mettre aussi sur le site en ligne d'Omeka.

**Comment by samszo** [comment]
OK les images sont uploader sur le serveur

**Comment by Honomatopic** [comment]
C'est étrange les images n’apparaissent toujours pas sur le site Omeka

**Comment by Honomatopic** [comment]
Pour les vignettes des questions, j'ai contourné le problème. Je clôture l'issue.
