### ISSUE TITLE
Récupérer les données de la base d'Omeka avec PHP ?

### ISSUE THREAD

**Issue by Honomatopic** [Honomatopic/Houdinews#18]
Bonjour. Pour récupérer les données, serai t-il possible de le faire en PHP ? Vous nous avez parlé de D3.js pour manipuler ses données mais en PHP c'est possible aussi je suppose. Sachant que moi, j'ai de bonnes notions en PHP orienté objet.

**Comment by samszo** [comment]
La pwa est hébergée sur Github dans lequel PHP ne fonctionne pas.
J'ai mis un exemple en ligne d'utilisation de d3.js pour afficher du json cf. https://samszo.github.io/DWM_19-20/samszo/omkAPI.html
le code est là : https://github.com/samszo/DWM_19-20/blob/master/samszo/omkAPI.html
Pour générer un json, il faut utiliser l'API d'omeka par exemple dans ton cas les items sont ici : http://193.54.152.41/DWM1920/Houdinews/api/items
Tu peux modifier les paramètres de la requête à l'API pour par exemple récupérer toutes les questions :
http://193.54.152.41/DWM1920/Houdinews/api/items?resource_class_id=114
114 étant l'identifiant de la class question cf. http://193.54.152.41/DWM1920/Houdinews/admin/item?resource_class_id=114
Pour les joueurs c'est : http://193.54.152.41/DWM1920/Houdinews/api/items?resource_class_id=112
etc...
Il faut enregistrer le json dans un répertoire "data" dans ton répertoire "pwa"
car le serveur n'est pas encore en https et donc le lien direct vers le json sera refusé.
Je travaille dessus pour régler ce problème...

**Comment by Honomatopic** [comment]
Et pour gérer l'authentification, il faut utilisé D3.js ? Car dans notre application, il y a une partie authentification avec un login et un mot de passe, et une partie inscription.

Après c'est dommage que l'on ne peut pas utilisé le PHP pour avoir une application complète. Car il y a du HTML, CSS, JQuery et JavaScript dans notre Web App. Avec PHP saura été un combo parfait...

**Comment by Honomatopic** [comment]
Bonsoir. Pour D3.js j'ai compris le principe. Je suis en train de le mettre en pratique. Je clôture l'issue.
