### ISSUE TITLE
Redimensionner les icones pour la Progressive Web App

### ISSUE THREAD

**Issue by Honomatopic** [Honomatopic/Houdinews#19]
Salut. Il faudrait que tu me donnes le vrai logo d'Houdinews dimensionné de différentes façons : 150*150px ; 192*192px ; 250*250px ; 380*380px ; 512*512px. Et les dimensions sont importantes à respecter. C'est pour la progressive web app.

**Comment by shraidy** [comment]
salut Honoré,
les images sont dans un dossier "objets graphiques" dans le template

**Comment by Honomatopic** [comment]
Salut Rudy. Merci je vais le traiter dans la journée.
