### ISSUE TITLE
Erreur 404 sur le serveur !

### ISSUE THREAD

**Issue by Honomatopic** [Honomatopic/Houdinews#21]
Bonjour. Sur le site d'Omeka en ligne à l'adresse suivante : http://193.54.152.41/DWM1920/Houdinews, il y a une erreur 404. Pire quand on se rend à l'adresse indiqué ci-dessus, on est redirigé vers celle-ci : http://193.54.152.31/digitaluses-congress/DWM1920/Houdinews. Pouvez-vous régler ce problème ?

**Comment by samszo** [comment]
OK c'est régélé

**Comment by Honomatopic** [comment]
Je cloture !
