### ISSUE TITLE
Concernant le dernier mail envoyé

### ISSUE THREAD

**Issue by Honomatopic** [Honomatopic/Houdinews#25]
Bonsoir. J'ai une question concernant le dernier mail que vous avez envoyé ce jeudi 2 avril avec la date du jury et les exemples des dossiers de conception. Dans la partie "finaliser la PWA", vous avez demandé : "afficher les données dans une liste" et "ajouter une interaction avec le choix dans la liste ". Or notre groupe à déjà afficher les données mais sans faire de listes et on a fait une interaction avec la réponse qui concerne la question. Est-ce-que notre groupe est obligé de faire ces deux points ? Le lien le voici : https://honomatopic.github.io/Houdinews/template/pwa/questionssamszofr.html

**Comment by samszo** [comment]
la page questionssamszofr.html est écrite en "dure", le travail que je demande consiste à l'écrire à partir des données JSON via D3.
Le concept de liste est très vaste dans votre cas ce sont les différentes questions et réponses.
Donc oui, il faut construire la page avec D3 à partir des données de OMK.

**Comment by Honomatopic** [comment]
Non je n'ai pas écrit en "dure" les données mais je les ai bien récupéré par le biais de D3.js. La page HTML CSS de questionssamszofr est ici : https://github.com/Honomatopic/Houdinews/blob/master/template/pwa/questionssamszofr.html et la question 1 (celle qui s'affiche à l'écran) est représenté par la balise <div id="laquestionun"></div> à la ligne 99 toujours dans la page énoncée précédemment. Le script D3.js est situé à la ligne 678 et s'appelle questionfr.js, la page est ici : https://github.com/Honomatopic/Houdinews/blob/master/template/pwa/bootstrap/js/questionfr.js La partie du code qui affiche la question 1 s'étend de la ligne 3 à la ligne 58. De la ligne 3 à la ligne 22, l'affichage de la question 1, de la ligne 24 à la ligne 40 l'affichage de la bonne réponse de la question 1. Et de la ligne 42 et la ligne 58 l'autre réponse de la question 1 (la mauvaise réponse). La réponse spécifique à la question 1 est sur cette page : https://github.com/Honomatopic/Houdinews/blob/master/template/pwa/bootstrap/js/reponsefr.js. De la ligne 2 à la ligne 30 concerne l'affichage de la vignette mais comme elle n'est pas sur Omeka, là je les généré en dure. De la ligne 31 à la ligne 46, la descriptif de la réponse et la source de l'information. Et de la ligne 47 à 52, c'est la gestion du point. De la ligne 53 à la ligne 93, c'est l'ensemble du script de la mauvaise réponse. Dans questionssamszofr.html, la balise à la ligne 108 <div id="autrereponseun"></div> affiche la mauvaise réponse, la balise à la ligne 115 <div id="bonnereponseun"></div> affiche la bonne réponse. Toujours dans questionssamszofr.html, à la ligne 147 <div id="descriptifun"></div> affiche le contenu de la réponse et la source.

Donc, est-ce-que on fait le travail demandé sous forme de liste quand même ?

**Comment by samszo** [comment]
OK je n'avais pas vu le code avec D3.
C'est bon pour l'exercice.
Par contre, il faudrait sans doute optimiser le code car il est très redondant et pas générique.
Si on ajoute une nouvelle question, il te faudra réécrire ton code js ce qui n'est pas très bon.
